Home:
	id: home
	name: "home"
	
	FloatLayout:
		id: bottom
		name: 'bottom'
		cols: 1
		canvas.before:
			Color:
				rgba: (2/255, 232/255, 144/255, 1)#(32/255, 74/255, 93/255, .5)
			Rectangle:
				size: self.size
				pos: self.pos
		canvas.after:
			Color:
				rgba: (1, 1, 1, 1)
			Line:
				rectangle: (20, bottom.size[1]*.02, 500, 650)
				width: 1.5
		
		MDGridLayout:
			cols: 1
			size_hint: 1, 1
			#size: bottom.size[0]/2, bottom.size[1]*.95
			#x: bottom.size[0]/2 - 20
			pos_hint: {'center_x': .5, 'center_y': .5}
			
			canvas.after:
				Color:
					rgba: (12/255, 19/255, 77/255, .8)
				
				RoundedRectangle:
					size: self.size[0]-dp(10), self.size[1]-dp(15)
					pos: self.pos[0]+dp(5), self.pos[1]+dp(7.5)
					source: "images/hacker.png"	
			
		BoxLayout:
			id: bottom2
			name: 'bottom2'

			orientation: 'vertical'
			elevation: 10
			size_hint: None, None
			size: 500, 650
			x: 20
			pos_hint: {'center_y': .5}
			
			canvas.before:
				Color:
					rgba: (32/255, 74/255, 93/255, 1)
				
				Rectangle:
					size: self.size
					pos: self.pos

			FloatLayout:
				cols: 1
				size_hint: (1, .8)
				canvas.before:
					Color:
						rgba: (.8, 0, 0, 1)
					Rectangle:
						size: self.size[0], self.size[1]*.5
						pos: bottom2.pos[0], bottom.size[1]*.765
					Ellipse:
						size: self.size[0], self.size[1]*1.05
						pos: bottom2.pos[0], bottom2.size[1]*.55

				Image:
					allow_stretch: True
					pos_hint: {'center_x': .5, 'center_y': .5}
					source: "images/logo.png"
			
			GridLayout:
				cols: 1
				padding: dp(5)
				
				MDLabel:
					text: '[b]Por favor, Seleccione una opción.[/b]'
					theme_text_color: 'Custom'
					text_color: (1, 1, 1, 1)
					font_size: dp(22)
					size_hint: 1, .4
					markup: True
					halign: 'left'
					#valign: 'center'
				
				FloatLayout:
					cols: 1
					padding: dp(5), dp(5), dp(5), dp(5)
					spacing: dp(5)
					
					MDRectangleFlatIconButton:
						text: "Iniciar Sesion"
						theme_text_color: 'Custom'
						text_color: (1, 1, 1, 1)
						line_color: (1, 1, 1, 1)
						icon: 'login'
						icon_color: (1, 1, 1, 1)
						disabled: False
						size_hint:  .7, .2
						pos_hint: {'top': 1}
						x: bottom2.pos[0] + 20
						on_release: app.root.current = "login"

					MDRectangleFlatIconButton:
						text: "Registrarse"
						theme_text_color: 'Custom'
						text_color: (1, 1, 1, 1)
						line_color: (1, 1, 1, 1)
						icon: 'pencil'
						icon_color: (1, 1, 1, 1)
						disabled: False
						size_hint: .7, .2
						pos_hint: {'top': .75}
						x: bottom2.pos[0] + 40
						on_release: app.root.current = "join"
						
					MDRectangleFlatIconButton:
						text: "Mas Información"
						theme_text_color: 'Custom'
						text_color: (1, 1, 1, 1)
						line_color: (1, 1, 1, 1)
						icon: 'information-outline'
						icon_color: (1, 1, 1, 1)
						disabled: False
						size_hint: .7, .2
						pos_hint: {'top': .5}
						x: bottom2.pos[0] + 20
						on_press: root.openDialog(title='Error', text='Lo sentimos, esta opción no funciona por el momento')
						
					MDRectangleFlatIconButton:
						text: "Ayuda"
						theme_text_color: 'Custom'
						text_color: (1, 1, 1, 1)
						line_color: (1, 1, 1, 1)
						icon: 'help'
						icon_color: (1, 1, 1, 1)
						disabled: False
						size_hint: .7, .2
						pos_hint: {'top': 0.25}
						x: bottom2.pos[0] + 40
						on_press: root.openDialog(title='Error', text='Lo sentimos, esta opción no funciona por el momento')